name: Build, Lint, & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: rc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly-2025-10-11
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mold clang

      - name: Setup Rust toolchain
        run: rustup toolchain install ${{ matrix.toolchain }}

      - name: Set RUSTFLAGS for Mold linker
        run: echo "RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=$(which mold)" >> $GITHUB_ENV

      - uses: Swatinem/rust-cache@v2

      - name: Cargo fmt check
        run: cargo fmt --check

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo test
        run: cargo test --verbose
